JAM-Brilliance/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;

using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class SearchController : Controller
    {
        private readonly ISearchDataService _searchDataService;
        private readonly ISurveyDataService _surveyDataService;
        private readonly IDiagnosticsService _diagnosticsService;
        private readonly IMapper _mapper;

        public SearchController(ISearchDataService searchDataService, ISurveyDataService surveyDataService, IDiagnosticsService diagnosticsService, IMapper mapper)
        {
            _searchDataService = searchDataService;
            _surveyDataService = surveyDataService;
            _diagnosticsService = diagnosticsService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult Search()
        {
            ViewBag.CurrentPageId = PageIds.Search;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var ss = new SearchCriteriaViewModel();
            return View(ss);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchCriteriaViewModel scvm)
        {
            ViewBag.CurrentPageId = PageIds.Search;

            if (ModelState.IsValid)
            {
                var sc = _mapper.Map<SearchCriteria>(scvm);
                var survey = _surveyDataService.GetCurrentUserSurvey();

                IEnumerable<SearchResult> srs = _searchDataService.SimpleSearch(sc, survey);

                var srvms = _mapper.Map<IEnumerable<SearchResult>, IList<SearchResultViewModel>>(srs);
                if (srvms.Count > 0)
                {
                    TempData[Constants.SearchResultTempDataName] = srvms;
                    return RedirectToAction("SearchResult");
                }
            }

            ViewBag.CurrentPageId = PageIds.Search;
            return View(scvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult SearchResult(int? page)
        {
            ViewBag.CurrentPageId = PageIds.Search;

            var srvms = (List<SearchResultViewModel>)TempData[Constants.SearchResultTempDataName];
            if (srvms != null)
            {
                TempData.Keep(Constants.SearchResultTempDataName);
            }
            else
            {
                srvms = new List<SearchResultViewModel>();
            }

            var pageNumber = page ?? 1;
            var onePageOfSearchResults = srvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfSearchResults = onePageOfSearchResults;

            return View(onePageOfSearchResults);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult SearchAdv()
        {
            ViewBag.CurrentPageId = PageIds.Search;

            var ssa = new SearchAdvCriteriaViewModel();

            return View(ssa);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ViewResult SearchAdv(SearchAdvCriteriaViewModel sacvm)
        {
            if (ModelState.IsValid)
            {
                var sac = _mapper.Map<SearchAdvCriteria>(sacvm);
                var survey = _surveyDataService.GetCurrentUserSurvey();

                IEnumerable<SearchResult> srs = _searchDataService.AdvancedSearch(sac, survey);

                var srvms = _mapper.Map<IEnumerable<SearchResult>, IList<SearchResultViewModel>>(srs);

                return View("SearchResult", srvms);
            }

            ViewBag.CurrentPageId = PageIds.Search;
            return View(sacvm);
        }
    }
}

JAM-Brilliance/Controllers/SurveyController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class SurveyController : Controller
    {
        private readonly IPictureDataService _pictureDataService;
        private readonly ISurveyDataService _surveyDataService;
        private readonly IAccountService _accountService;
        private readonly IVisitorDataService _historyService;
        private readonly IGeoService _geoService;
        private readonly IDataCache _dataCache;
        private readonly IMapper _mapper;
        public SurveyController(ISurveyDataService surveyDataService, IPictureDataService pictureDataService, IAccountService accountService, IVisitorDataService visitorDataService, IGeoService geoService, IDataCache dataCache, IMapper mapper)
        {
            _pictureDataService = pictureDataService;
            _surveyDataService = surveyDataService;
            _accountService = accountService;
            _historyService = visitorDataService;
            _geoService = geoService;
            _dataCache = dataCache;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult Details(int surveyId)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            Survey survey = _surveyDataService.GetSurvey(surveyId);

            var svm = new SurveyViewModel();
            svm.Page1 =_mapper.Map<SurveyPage1ViewModel>(survey);
            svm.Page2 =_mapper.Map<SurveyPage2ViewModel>(survey);
            svm.Page3 =_mapper.Map<SurveyPage3ViewModel>(survey);
            svm.Page4 =_mapper.Map<SurveyPage4ViewModel>(survey);
            svm.Page5 =_mapper.Map<SurveyPage5ViewModel>(survey);
            svm.Page6 =_mapper.Map<SurveyPage6ViewModel>(survey);
            svm.SetAsReadOnly();

            svm.Page1.KidsCounts = _dataCache.Kids;
            svm.Page1.KidsWantedCounts = _dataCache.KidsWanted;
            svm.Page1.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;
            svm.Page6.WantedKidsWantedCounts = _dataCache.WantedKidsWanted;
            svm.Page6.Referrers = _dataCache.Referrers;

            return View(svm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ShortDetails(int surveyId)
        {
            var selfSurveyId = _surveyDataService.GetCurrentUserSurveyId();

            Task.Run(() => _historyService.AddVisitor(new HistoryEntry { SelfSurveyId = selfSurveyId, OtherSurveyId = surveyId }));

            var survey = _surveyDataService.GetSurvey(surveyId);
            var ssvm = _mapper.Map<ShortSurveyViewModel>(survey);
            ssvm.LastActivityDate = _accountService.GetCurrentUserLastActivity(survey.Email);

            return View(ssvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyShortDetails()
        {
            HttpContext.Response.Cookies.Set(new HttpCookie(Constants.CultureCookieName, _accountService.GetCurrentUserCommentCultureCode()));

            var survey = _surveyDataService.GetCurrentUserSurvey();
            var ssvm = _mapper.Map<ShortSurveyViewModel>(survey);
            ssvm.LastActivityDate = _accountService.GetCurrentUserLastActivity(survey.Email);
            
            return View(ssvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult Page1(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            var sp1Vm = _mapper.Map<SurveyPage1ViewModel>(survey);

            sp1Vm.KidsCounts = _dataCache.Kids;
            sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
            sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

            return View(sp1Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page1(SurveyPage1ViewModel sp1Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                sp1Vm.PostalCode = sp1Vm.PostalCode.Replace(" ", "");
                var partSurvey = GetAllowedPartSurvey(sp1Vm);

                if (_surveyDataService.SavePage1(partSurvey))
                {
                    Task.Run(() => _geoService.LookupAndStoreGeoCoordinates(partSurvey.SurveyId, partSurvey.PostalCode, partSurvey.City, partSurvey.Country));
                }

                HttpPostedFileBase pictureFile = Request.Files["OriginalLocation"];

                if (pictureFile != null && pictureFile.ContentLength > 0)
                {
                    var pic = _pictureDataService.LoadBytesIntoPicture(pictureFile);
                    if (pic != null)
                    {
                        pic.SurveyId = partSurvey.SurveyId;
                        int pictureId = _pictureDataService.SaveMainPicture(pic);
                    }
                    else
                    {
                        int length = pictureFile.ContentLength;
                        string ftype = pictureFile.ContentType;
                        int kiloLength = length / 1000;
                        string ftypeEnd = ftype != null && ftype.IndexOf('/') > 0 ? ftype.Substring(ftype.IndexOf('/') + 1) : "-";

                        var fel = string.Format("Bilden får vara max 1500kb stor och måste vara jpeg eller png.{0}Din bild var {1}kb och {2}", Environment.NewLine, kiloLength, ftypeEnd);
                        ModelState.AddModelError("PictureDummyId", fel);
                        sp1Vm.KidsCounts = _dataCache.Kids;
                        sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
                        sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

                        return View(sp1Vm);
                    }
                }

                if (direction.Equals(PageButtons.NextPage))
                {
                    return RedirectToAction("Page2", new { surveyId = sp1Vm.SurveyId });
                }

                return RedirectToAction("Page1", new { surveyId = sp1Vm.SurveyId });
            }

            sp1Vm.KidsCounts = _dataCache.Kids;
            sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
            sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

            return View(sp1Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page2(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp2Vm = _mapper.Map<SurveyPage2ViewModel>(survey);

            return View(sp2Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page2(SurveyPage2ViewModel sp2Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp2Vm);

                bool ok = _surveyDataService.SavePage2(partSurvey);

                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page1", new { surveyId = sp2Vm.SurveyId });
                }

                return RedirectToAction("Page3", new { surveyId = sp2Vm.SurveyId });
            }

            return View(sp2Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page3(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp3Vm = _mapper.Map<SurveyPage3ViewModel>(survey);

            return View(sp3Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page3(SurveyPage3ViewModel sp3Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp3Vm);

                bool ok = _surveyDataService.SavePage3(partSurvey);
                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page2", new { surveyId = sp3Vm.SurveyId });
                }

                return RedirectToAction("Page4", new { surveyId = sp3Vm.SurveyId });
            }

            return View(sp3Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page4(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp4Vm = _mapper.Map<SurveyPage4ViewModel>(survey);

            return View(sp4Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page4(SurveyPage4ViewModel sp4Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp4Vm);

                bool ok = _surveyDataService.SavePage4(partSurvey);
                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page3", new { surveyId = sp4Vm.SurveyId });

JAM-Brilliance/Controllers/VisitorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class VisitorController : Controller
    {
        private readonly ISurveyDataService _surveyDataService;
        private readonly IVisitorDataService _visitorDataService;
        private readonly IDiagnosticsService _diagnosticsService;
        private readonly IMapper _mapper;

        public VisitorController(ISurveyDataService surveyDataService, IVisitorDataService visitorDataService, IDiagnosticsService diagnosticsService, IMapper mapper)
        {
            _surveyDataService = surveyDataService;
            _visitorDataService = visitorDataService;
            _diagnosticsService = diagnosticsService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyVisitors(int? page)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var svvms = GetMySortedVisitors();

            var pageNumber = page ?? 1;
            var onePageOfVisitors = svvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfVisitors = onePageOfVisitors;

            return View(onePageOfVisitors);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyVisits(int? page)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var svvms = GetMySortedVisits();

            var pageNumber = page ?? 1;
            var onePageOfVisits = svvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfVisits = onePageOfVisits;

            return View(onePageOfVisits);
        }

        private IEnumerable<HistoryEntryViewModel> GetMySortedVisitors()
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            IEnumerable<HistoryEntry> hms = _visitorDataService.GetVisitors(surveyId);
            var hvms = _mapper.Map<IEnumerable<HistoryEntry>, IList<HistoryEntryViewModel>>(hms);

            IEnumerable<HistoryEntryViewModel> smvms = hvms.OrderByDescending(x => x.LastVisitDate);
            return smvms;
        }

        private IEnumerable<HistoryEntryViewModel> GetMySortedVisits()
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            IEnumerable<HistoryEntry> hms = _visitorDataService.GetVisits(surveyId);
            var hvms = _mapper.Map<IEnumerable<HistoryEntry>, IList<HistoryEntryViewModel>>(hms);

            IEnumerable<HistoryEntryViewModel> smvms = hvms.OrderByDescending(x => x.LastVisitDate);
            return smvms;
        }
    }
}

JAM-Brilliance/Views/Shared/Footer.cshtml
@using JAM.Brilliance.App_GlobalResources

<div id="footer-box" class="no-print">
    <table width="100%" class="container">
        <tr>
            <td style="vertical-align: top;">
                
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;">
               
            </td>
        </tr>
    </table>
</div>
<table width="100%" id="footer" class="no-print">
    <tr>
        <td style="vertical-align: top;">
            @Html.Raw(Global.Constants_Copyright)
        </td>
    </tr>
</table>

JAM-Brilliance/Views/Shared/Header.cshtml
@using JAM.Brilliance.App_GlobalResources
@using JAM.Core.Logic

<table width="100%" id="header" class="no-print">
    <tr>
        <td>
            <table width="100%" class="container">
                <tr>
                    <td>
                        <div id="title">
                            <div class="caption">
                                @Constants.Title
                            </div>
                            <div class="subcaption">
                                
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

JAM-Brilliance/Views/Shared/Menu.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@using JAM.Brilliance.App_GlobalResources
@model MyPageViewModel
@if (Model.IsMember)
{
    <script>
        $(document).ready(checkMessages('@Url.Action("GetNumberOfUnreadMessages", "Message")'));
    </script>
}

<table width="100%" id="main-nav" class="container">
    <tr>
        <td>
            <div id="menu">
                <nav class="nav">
                    <ul class="nav-list">
                        @if (Model.IsMember)
                        {
                            <li class="nav-item @(Model.CurrentPageId == PageIds.Start ? "active" : "")">@Html.ActionLink(@Global.Menu_Start, "Start", "Home")</li>
                            <li class="nav-item @(Model.CurrentPageId == PageIds.Search ? "active" : "")">@Html.ActionLink(@Global.Menu_Search, "Search", "Search") <i class="fa fa-search"></i></li>
                            <li class="nav-item @(Model.CurrentPageId == PageIds.Contact ? "active" : "")">@Html.ActionLink(@Global.Menu_ContactUs, "Contact", "Home")</li>
                            <li class="nav-item @(Model.CurrentPageId == PageIds.MyPage ? "active" : "")">
                                @Html.ActionLink("Min profil", "MyShortDetails", "Survey")
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("MyMessages", "Message")" title="Mina meddelande" id="MessagesLink">
                                    <i class="fa fa-envelope"></i><sup id="MessagesCountTop">&nbsp;&nbsp;</sup>
                                </a>
                            </li>
                        }
                        
                        @if (Model.IsAdmin)
                        {
                            <li class="nav-item @(Model.CurrentPageId == PageIds.DevPage ? "active" : "")">
                                <a href="@Url.Action("DevPage", "Home")"><i class="fa fa-cogs fa-spin"></i></a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </td>
    </tr>
</table>

JAM-Brilliance/Views/Shared/ProfileMenu.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@using JAM.Brilliance.App_GlobalResources
@model MyPageViewModel

<fieldset>
    <legend>Min Profil <i class="fa fa-list-ul"></i></legend>
    <sup>&nbsp;</sup>

    @Html.ActionLink("Editera profil", "Page1", "Survey")
    
</fieldset>

JAM-Brilliance/Views/Shared/SurveyIncompleteError.cshtml
@using JAM.Core.Exceptions
@model HandleErrorInfo

<div>
    @if (Model != null && Model.Exception is SurveyIncompleteException)
    {
        <div>
            <fieldset>
                <legend>OBS</legend>
                <p>Du nåste fylla i din profil för att komma åt sökningar, meddelande, favoriter etc</p>
                <p>Gå till @Html.ActionLink("Mina profil", "MyShortDetails", "Survey")</p>
            </fieldset>
        </div>
        <br /><br /><br /><br />
    }
    else
    {
        <p>Systemfel!</p>
        <br /><br /><br /><br /><br /><br /><br /><br /><br />
    }
</div>

JAM-Brilliance/Views/Shared/ToolbarAdmin.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@model MyPageViewModel

<script>
    $(document).ready(checkAdminCounts('@Url.Action("GetAdminNumbersOf", "PictureAdmin")'));
</script>

<fieldset>
    <legend>Administration <i class="fa fa-cogs fa-spin"></i></legend>
    &nbsp;
    <a href="@Url.Action("Start", "SurveyAdmin")">Profiler<i style="padding-left: 5px;" class="fa fa-female"></i></a>
    &nbsp;&nbsp;
    <a href="@Url.Action("Start", "AccountAdmin")">ASP.NET Accounts<i style="padding-left: 5px;" class="fa fa-male"></i></a>
    &nbsp;&nbsp;
    <a href="@Url.Action("Start", "AbuseAdmin")">Anmälningar<i style="padding-left: 5px;" class="fa fa-bullhorn"></i></a><sup id="AbuseReportsCount">&nbsp;&nbsp;</sup>
    &nbsp; &nbsp;
    <a href="@Url.Action("Start", "PictureAdmin")">Väntande Bilder<i style="padding-left: 5px;" class="fa fa-file-image-o"></i></a><sup id="PicturesWaitingCount">&nbsp;&nbsp;</sup>
    &nbsp; &nbsp;
    <a href="@Url.Action("SupportMessages", "MessageAdmin", new { surveyId = 1 }, null)" title="Meddelande till support">Support<i style="padding-left: 5px;" class="fa fa-envelope"></i></a><sup id="SupportMessagesCount">&nbsp;&nbsp;</sup>
    &nbsp;&nbsp;
    <a href="@Url.Action("SupportMessages", "MessageAdmin", new { surveyId = 2 }, null)" title="Meddelande till anonym support">Support A<i style="padding-left: 5px;" class="fa fa-envelope"></i></a><sup id="AnonSupportMessagesCount">&nbsp;&nbsp;</sup>
    &nbsp;&nbsp;
    <a href="@Url.Action("BroadcastMessage", "MessageAdmin")" title="Skicka meddelande till alla">Multi<i style="padding-left: 5px;" class="fa fa-envelope-square"></i></a>
    &nbsp;&nbsp;
    <a href="@Url.Action("LogEntries", "AccountAdmin")" title="Öppna Loggen"><i style="padding-left: 5px;" class="fa fa-align-justify"></i></a>
    &nbsp; &nbsp;
    <a href="@Url.Action("Start", "MaintenanceAdmin")" title="Underhåll"><i style="padding-left: 5px;" class="fa fa-trash"></i></a>
</fieldset>

JAM-Brilliance/Views/Shared/ToolbarUser.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@model MyPageViewModel

@if (Model.IsSurveyComplete)
{
    var visitorIcon = "fa-female";
    if (Model.IsSearchigForMale)
    {
        visitorIcon = "fa-male";
    }
    <script>
        $(document).ready(checkCounts('@Url.Action("GetNumbersOf", "Message")'));
    </script>

    <fieldset>
        <legend>Mina sidor <i class="fa fa-bolt"></i></legend>
        &nbsp;
        <a href="@Url.Action("Search", "Search")">Sök<i style="padding-left: 5px;" class="fa fa-search"></i></a>
        &nbsp;&nbsp;
        <a href="@Url.Action("MyMessages", "Message")">Meddelande<i style="padding-left: 5px;" class="fa fa-envelope"></i></a><sup id="MessagesCount">&nbsp;&nbsp;</sup>
        &nbsp;&nbsp;
        <a href="@Url.Action("MyVisitors", "Visitor")">Besökare<i style="padding-left: 5px;" class="fa @visitorIcon"></i></a><sup id="VisitorsCount">&nbsp;&nbsp;</sup>
        &nbsp;&nbsp;
        <a href="@Url.Action("MyFavourites", "Favourite")">Favoriter<i style="padding-left: 5px;" class="fa fa-heart"></i></a>
        &nbsp; &nbsp;
        <a href="@Url.Action("OnlineUsers", "Account")">Online<i style="padding-left: 5px; color: green;" class="fa fa-circle"></i></a><sup id="OnlineCount">&nbsp;&nbsp;</sup>
        &nbsp; &nbsp;
        <a href="@Url.Action("MyShortDetails", "Survey")">Min profil<i style="padding-left: 5px;" class="fa fa-list-ul"></i></a>
        &nbsp;&nbsp;
        <a href="@Url.Action("MyPictures", "Picture")">Mina bilder<i style="padding-left: 5px;" class="fa fa-file-image-o"></i></a>
        &nbsp;&nbsp;
        <a href="@Url.Action("MyActions", "Home")">Inställningar<i style="padding-left: 5px;" class="fa fa-cog"></i></a>
    </fieldset>
}