JAM-Brilliance/Controllers/FavouriteController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class FavouriteController : Controller
    {
        private readonly ISurveyDataService _surveyDataService;
        private readonly IFavouriteDataService _favouriteDataService;
        private readonly IDiagnosticsService _diagnosticsService;
        private readonly IMapper _mapper;

        public FavouriteController(ISurveyDataService surveyDataService, IFavouriteDataService favouriteDataService, IDiagnosticsService diagnosticsService, IMapper mapper)
        {
            _surveyDataService = surveyDataService;
            _favouriteDataService = favouriteDataService;
            _diagnosticsService = diagnosticsService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyFavourites(int? page)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var fvms = GetMySortedFavourites();

            var pageNumber = page ?? 1;
            var onePageOfFavourites = fvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfFavourites = onePageOfFavourites;

            return View(onePageOfFavourites);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyFans(int? page)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var fvms = GetMySortedFans();

            var pageNumber = page ?? 1;
            var onePageOfFans = fvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfFans = onePageOfFans;

            return View(onePageOfFans);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult AddFavourite(int otherSurveyId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            var fav = new Favourite();
            fav.SelfSurveyId = surveyId;
            fav.OtherSurveyId = otherSurveyId;

            bool ok = _favouriteDataService.AddFavourite(fav);

            return RedirectToAction("MyFavourites");
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult RemoveFavourite(int favouriteId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            var fav = new Favourite();
            fav.SelfSurveyId = surveyId;
            fav.FavouriteId = favouriteId;

            bool ok = _favouriteDataService.RemoveFavourite(fav);

            return RedirectToAction("MyFavourites");
        }

        private IEnumerable<FavouriteViewModel> GetMySortedFavourites()
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            IEnumerable<Favourite> fms = _favouriteDataService.GetFavourites(surveyId);
            var fvms = _mapper.Map<IEnumerable<Favourite>, IList<FavouriteViewModel>>(fms);

            IEnumerable<FavouriteViewModel> smvms = fvms.OrderBy(x => x.OtherName);
            return smvms;
        }

        private IEnumerable<FavouriteViewModel> GetMySortedFans()
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            IEnumerable<Favourite> fms = _favouriteDataService.GetFans(surveyId);
            var fvms = _mapper.Map<IEnumerable<Favourite>, IList<FavouriteViewModel>>(fms);

            IEnumerable<FavouriteViewModel> smvms = fvms.OrderBy(x => x.SelfName);
            return smvms;
        }
    }
}

JAM-Brilliance/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;

using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class SearchController : Controller
    {
        private readonly ISearchDataService _searchDataService;
        private readonly ISurveyDataService _surveyDataService;
        private readonly IDiagnosticsService _diagnosticsService;
        private readonly IMapper _mapper;

        public SearchController(ISearchDataService searchDataService, ISurveyDataService surveyDataService, IDiagnosticsService diagnosticsService, IMapper mapper)
        {
            _searchDataService = searchDataService;
            _surveyDataService = surveyDataService;
            _diagnosticsService = diagnosticsService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult Search()
        {
            ViewBag.CurrentPageId = PageIds.Search;

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var ss = new SearchCriteriaViewModel();
            return View(ss);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchCriteriaViewModel scvm)
        {
            ViewBag.CurrentPageId = PageIds.Search;

            if (ModelState.IsValid)
            {
                var sc = _mapper.Map<SearchCriteria>(scvm);
                var survey = _surveyDataService.GetCurrentUserSurvey();

                IEnumerable<SearchResult> srs = _searchDataService.SimpleSearch(sc, survey);

                var srvms = _mapper.Map<IEnumerable<SearchResult>, IList<SearchResultViewModel>>(srs);
                if (srvms.Count > 0)
                {
                    TempData[Constants.SearchResultTempDataName] = srvms;
                    return RedirectToAction("SearchResult");
                }
            }

            ViewBag.CurrentPageId = PageIds.Search;
            return View(scvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult SearchResult(int? page)
        {
            ViewBag.CurrentPageId = PageIds.Search;

            var srvms = (List<SearchResultViewModel>)TempData[Constants.SearchResultTempDataName];
            if (srvms != null)
            {
                TempData.Keep(Constants.SearchResultTempDataName);
            }
            else
            {
                srvms = new List<SearchResultViewModel>();
            }

            var pageNumber = page ?? 1;
            var onePageOfSearchResults = srvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfSearchResults = onePageOfSearchResults;

            return View(onePageOfSearchResults);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult SearchAdv()
        {
            ViewBag.CurrentPageId = PageIds.Search;

            var ssa = new SearchAdvCriteriaViewModel();

            return View(ssa);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ViewResult SearchAdv(SearchAdvCriteriaViewModel sacvm)
        {
            if (ModelState.IsValid)
            {
                var sac = _mapper.Map<SearchAdvCriteria>(sacvm);
                var survey = _surveyDataService.GetCurrentUserSurvey();

                IEnumerable<SearchResult> srs = _searchDataService.AdvancedSearch(sac, survey);

                var srvms = _mapper.Map<IEnumerable<SearchResult>, IList<SearchResultViewModel>>(srs);

                return View("SearchResult", srvms);
            }

            ViewBag.CurrentPageId = PageIds.Search;
            return View(sacvm);
        }
    }
}

JAM-Brilliance/Controllers/SurveyController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class SurveyController : Controller
    {
        private readonly IPictureDataService _pictureDataService;
        private readonly ISurveyDataService _surveyDataService;
        private readonly IAccountService _accountService;
        private readonly IVisitorDataService _historyService;
        private readonly IGeoService _geoService;
        private readonly IDataCache _dataCache;
        private readonly IMapper _mapper;
        public SurveyController(ISurveyDataService surveyDataService, IPictureDataService pictureDataService, IAccountService accountService, IVisitorDataService visitorDataService, IGeoService geoService, IDataCache dataCache, IMapper mapper)
        {
            _pictureDataService = pictureDataService;
            _surveyDataService = surveyDataService;
            _accountService = accountService;
            _historyService = visitorDataService;
            _geoService = geoService;
            _dataCache = dataCache;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult Details(int surveyId)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            Survey survey = _surveyDataService.GetSurvey(surveyId);

            var svm = new SurveyViewModel();
            svm.Page1 =_mapper.Map<SurveyPage1ViewModel>(survey);
            svm.Page2 =_mapper.Map<SurveyPage2ViewModel>(survey);
            svm.Page3 =_mapper.Map<SurveyPage3ViewModel>(survey);
            svm.Page4 =_mapper.Map<SurveyPage4ViewModel>(survey);
            svm.Page5 =_mapper.Map<SurveyPage5ViewModel>(survey);
            svm.Page6 =_mapper.Map<SurveyPage6ViewModel>(survey);
            svm.SetAsReadOnly();

            svm.Page1.KidsCounts = _dataCache.Kids;
            svm.Page1.KidsWantedCounts = _dataCache.KidsWanted;
            svm.Page1.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;
            svm.Page6.WantedKidsWantedCounts = _dataCache.WantedKidsWanted;
            svm.Page6.Referrers = _dataCache.Referrers;

            return View(svm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ShortDetails(int surveyId)
        {
            var selfSurveyId = _surveyDataService.GetCurrentUserSurveyId();

            Task.Run(() => _historyService.AddVisitor(new HistoryEntry { SelfSurveyId = selfSurveyId, OtherSurveyId = surveyId }));

            var survey = _surveyDataService.GetSurvey(surveyId);
            var ssvm = _mapper.Map<ShortSurveyViewModel>(survey);
            ssvm.LastActivityDate = _accountService.GetCurrentUserLastActivity(survey.Email);

            return View(ssvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyShortDetails()
        {
            HttpContext.Response.Cookies.Set(new HttpCookie(Constants.CultureCookieName, _accountService.GetCurrentUserCommentCultureCode()));

            var survey = _surveyDataService.GetCurrentUserSurvey();
            var ssvm = _mapper.Map<ShortSurveyViewModel>(survey);
            ssvm.LastActivityDate = _accountService.GetCurrentUserLastActivity(survey.Email);
            
            return View(ssvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult Page1(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            var sp1Vm = _mapper.Map<SurveyPage1ViewModel>(survey);

            sp1Vm.KidsCounts = _dataCache.Kids;
            sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
            sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

            return View(sp1Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page1(SurveyPage1ViewModel sp1Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                sp1Vm.PostalCode = sp1Vm.PostalCode.Replace(" ", "");
                var partSurvey = GetAllowedPartSurvey(sp1Vm);

                if (_surveyDataService.SavePage1(partSurvey))
                {
                    Task.Run(() => _geoService.LookupAndStoreGeoCoordinates(partSurvey.SurveyId, partSurvey.PostalCode, partSurvey.City, partSurvey.Country));
                }

                HttpPostedFileBase pictureFile = Request.Files["OriginalLocation"];

                if (pictureFile != null && pictureFile.ContentLength > 0)
                {
                    var pic = _pictureDataService.LoadBytesIntoPicture(pictureFile);
                    if (pic != null)
                    {
                        pic.SurveyId = partSurvey.SurveyId;
                        int pictureId = _pictureDataService.SaveMainPicture(pic);
                    }
                    else
                    {
                        int length = pictureFile.ContentLength;
                        string ftype = pictureFile.ContentType;
                        int kiloLength = length / 1000;
                        string ftypeEnd = ftype != null && ftype.IndexOf('/') > 0 ? ftype.Substring(ftype.IndexOf('/') + 1) : "-";

                        var fel = string.Format("Bilden får vara max 1500kb stor och måste vara jpeg eller png.{0}Din bild var {1}kb och {2}", Environment.NewLine, kiloLength, ftypeEnd);
                        ModelState.AddModelError("PictureDummyId", fel);
                        sp1Vm.KidsCounts = _dataCache.Kids;
                        sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
                        sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

                        return View(sp1Vm);
                    }
                }

                if (direction.Equals(PageButtons.NextPage))
                {
                    return RedirectToAction("Page2", new { surveyId = sp1Vm.SurveyId });
                }

                return RedirectToAction("Page1", new { surveyId = sp1Vm.SurveyId });
            }

            sp1Vm.KidsCounts = _dataCache.Kids;
            sp1Vm.KidsWantedCounts = _dataCache.KidsWanted;
            sp1Vm.WhatSearchingForWhats = _dataCache.WhatSearchingForWhats;

            return View(sp1Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page2(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp2Vm = _mapper.Map<SurveyPage2ViewModel>(survey);

            return View(sp2Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page2(SurveyPage2ViewModel sp2Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp2Vm);

                bool ok = _surveyDataService.SavePage2(partSurvey);

                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page1", new { surveyId = sp2Vm.SurveyId });
                }

                return RedirectToAction("Page3", new { surveyId = sp2Vm.SurveyId });
            }

            return View(sp2Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page3(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp3Vm = _mapper.Map<SurveyPage3ViewModel>(survey);

            return View(sp3Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page3(SurveyPage3ViewModel sp3Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp3Vm);

                bool ok = _surveyDataService.SavePage3(partSurvey);
                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page2", new { surveyId = sp3Vm.SurveyId });
                }

                return RedirectToAction("Page4", new { surveyId = sp3Vm.SurveyId });
            }

            return View(sp3Vm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult Page4(int? surveyId)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            Survey survey = GetAllowedSurvey(surveyId);
            if (survey.SurveyId == 0)
            {
                return RedirectToAction("Page1", new { surveyId = surveyId });
            }

            var sp4Vm = _mapper.Map<SurveyPage4ViewModel>(survey);

            return View(sp4Vm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        [ValidateAntiForgeryToken]
        public ActionResult Page4(SurveyPage4ViewModel sp4Vm, string direction)
        {
            if (ModelState.IsValid)
            {
                var partSurvey = GetAllowedPartSurvey(sp4Vm);

                bool ok = _surveyDataService.SavePage4(partSurvey);
                if (direction.Equals(PageButtons.PreviousPage))
                {
                    return RedirectToAction("Page3", new { surveyId = sp4Vm.SurveyId });

JAM-Brilliance/Views/Search/Search.cshtml
@using JAM.Brilliance.Models.ViewModels
@using JAM.Brilliance.App_GlobalResources
@model SearchCriteriaViewModel
@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
<script>
    $(function () {
        $("#slider-agerange").slider({
            range: true,
            min: 18,
            max: 85,
            values: [25, 45],
            slide: function (event, ui) {
                $("#agerangetext").text($("#slider-agerange").slider("values", 0) + " -> " + $("#slider-agerange").slider("values", 1));
                $("#@Html.IdFor(model => model.AgeMin)").val(ui.values[0]);
                $("#@Html.IdFor(model => model.AgeMax)").val(ui.values[1]);
            }
        });

        $("#slider-heightrange").slider({
            range: true,
            min: 118,
            max: 210,
            values: [158, 199],
            slide: function (event, ui) {
                $("#heightrangetext").text($("#slider-heightrange").slider("values", 0) + " -> " + $("#slider-heightrange").slider("values", 1));
                $("#@Html.IdFor(model => model.HeightMin)").val(ui.values[0]);
                $("#@Html.IdFor(model => model.HeightMax)").val(ui.values[1]);
            }
        });

        $("#agerangetext").text($("#slider-agerange").slider("values", 0) + " -> " + $("#slider-agerange").slider("values", 1));
        $("#heightrangetext").text($("#slider-heightrange").slider("values", 0) + " -> " + $("#slider-heightrange").slider("values", 1));

        $("#@Html.IdFor(model => model.AgeMin)").val($("#slider-agerange").slider("values", 0));
        $("#@Html.IdFor(model => model.AgeMax)").val($("#slider-agerange").slider("values", 1));

        $("#@Html.IdFor(model => model.HeightMin)").val($("#slider-heightrange").slider("values", 0));
        $("#@Html.IdFor(model => model.HeightMax)").val($("#slider-heightrange").slider("values", 1));

    });
</script>
@{ Html.RenderAction("ToolbarUser", "Home"); }

<p>
    <br />
    @Global.Search_P1 @Html.ActionLink(Global.Search_Adv, "SearchAdv") @Global.Search_And @Global.Search_Quick
    <br />
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>Snabbsök</legend>
            <img src="/content/images/ja/holdinghands.jpg" alt="" width="400" style="float: right;" />
            <div class="editor-label">
                @Html.LabelFor(model => model.City)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.City, new { autofocus = "" })
                @Html.ValidationMessageFor(model => model.City)
            </div>
            
            <div class="editor-label">
                @Html.LabelFor(model => model.AgeMin) 
                (<span id="agerangetext"></span>)
            </div>
            <div class="editor-field">
                <div id="slider-agerange" style="max-width: 40%"></div>
               
                @Html.HiddenFor(model => model.AgeMin)
                @Html.HiddenFor(model => model.AgeMax)
                @Html.ValidationMessageFor(model => model.AgeMin)
            </div>
            
            <div class="editor-label">
                @Html.LabelFor(model => model.HeightMin)
                (<span id="heightrangetext"></span>)
            </div>
            <div class="editor-field">
                <div id="slider-heightrange" style="max-width: 40%"></div>
                
                @Html.HiddenFor(model => model.HeightMin)
                @Html.HiddenFor(model => model.HeightMax)
                @Html.ValidationMessageFor(model => model.HeightMin)
            </div>
            
            <div class="editor-label">
         
                @Html.CheckBoxFor(model => model.HasKids)
                @Html.LabelFor(model => model.HasKids)
                @Html.ValidationMessageFor(model => model.HasKids)
            </div>

            <div>
                <br />
                <button type="submit">
                    Sök <i class="fa fa-search"></i>
                </button>
            </div>
        </fieldset>
    }
</p>

JAM-Brilliance/Views/Search/SearchAdv.cshtml
@using JAM.Brilliance.App_GlobalResources.Survey
@using JAM.Brilliance.Models.ViewModels
@using JAM.Brilliance.App_GlobalResources
@model SearchAdvCriteriaViewModel
@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
@{ Html.RenderAction("ToolbarUser", "Home"); }

<p>
    <br />
    @Global.Search_P1 @Global.Search_Adv @Global.Search_And @Html.ActionLink(Global.Search_Quick, "Search")
    <br />
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>@SurveyTexts.Signup_Title</legend>
            <img src="/content/images/ja/holdinghands.jpg" alt="" width="400" style="float: right;" />

            <div>ADV Not done</div>
        </fieldset>
    }
</p>

JAM-Brilliance/Views/Search/SearchResult.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@using JAM.Brilliance.App_GlobalResources
@using PagedList
@using PagedList.Mvc
@model IEnumerable<SearchResultViewModel>

@{ Html.RenderAction("ToolbarUser", "Home"); }

<p>
    <br />
    @Global.Search_P1 @Html.ActionLink(Global.Search_Adv, "SearchAdv") @Global.Search_And @Global.Search_Quick
    <br />
</p>
<p>
    <fieldset>
        <legend>Sökresultat</legend>
        <table class="list-table">
            <tr>
                <th>Bild</th>
                <th>Namn</th>
                <th>Stad</th>
                <th>Ålder</th>
                <th>Längd</th>
                <th>Kontakta</th>
                <th>Gilla</th>
            </tr>
            @foreach (SearchResultViewModel sr in Model)
            {
                <tr>
                    <td><img class="list-picture" src="@Url.Action("MainPictureDataFor", "Picture", new { surveyId = sr.SurveyId })" /></td>
                    <td>@Html.ActionLink(sr.Name.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = sr.SurveyId }, null)</td>
                    <td>@sr.City.GetBeginning(StringLength.Long)</td>
                    <td>@sr.Age</td>
                    <td>@sr.Height</td>
                    <td class="padded-table-cell-centered">
                        <a href="@Url.Action("SendMessage", "Message", new { toSurveyId = sr.SurveyId })">
                            <i class="fa fa-envelope"></i>
                        </a>
                    </td>
                    <td class="padded-table-cell-centered">
                        <a href="@Url.Action("AddFavourite", "Favourite", new { otherSurveyId = sr.SurveyId })">
                            <i class="fa fa-heart"></i>
                        </a>
                    </td>
                </tr>
            }
        </table>
        @if (ViewBag.OnePageOfSearchResults != null)
        {
            @Html.PagedListPager((IPagedList)ViewBag.OnePageOfSearchResults, page => Url.Action("SearchResult", new { page }))

        }
    </fieldset>
</p>