JAM-Brilliance/Controllers/AbuseController.cs
using System.Web.Mvc;
using System.Web.SessionState;

using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class AbuseController : Controller
    {
        private readonly IAbuseDataService _abuseDataService;
        private readonly ISurveyDataService _surveyDataService;

        public AbuseController(IAbuseDataService abuseDataService, ISurveyDataService surveyDataService)
        {
            _abuseDataService = abuseDataService;
            _surveyDataService = surveyDataService;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult ReportSurvey(int fromSurveyId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            var arm = new AbuseReport();
            arm.OtherSurveyId = fromSurveyId;
            arm.SelfSurveyId = surveyId;

            _abuseDataService.ReportSurveyAbuse(arm);
            return RedirectToAction("MyShortDetails", "Survey");
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult ReportMessage(int messageId, int fromSurveyId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            var arm = new AbuseReport();
            arm.OtherSurveyId = fromSurveyId;
            arm.SelfSurveyId = surveyId;
            arm.MessageId = messageId;

            _abuseDataService.ReportMessageAbuse(arm);
            return RedirectToAction("MyShortDetails", "Survey");
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult ReportPicture(int pictureId, int ownerSurveyId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            var arm = new AbuseReport();
            arm.OtherSurveyId = ownerSurveyId;
            arm.SelfSurveyId = surveyId;
            arm.PictureId = pictureId;

            _abuseDataService.ReportPictureAbuse(arm);
            return RedirectToAction("MyShortDetails", "Survey");
        }
    }
}

JAM-Brilliance/Controllers/MessageAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;
using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Interfaces.Admin;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;
using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.ReadOnly)]
    [Authorize(Roles = MemberRoles.Administrator)]
    public class MessageAdminController : Controller
    {
        private readonly IMessageAdminDataService _messageAdminDataService;
        private readonly ISurveyAdminDataService _surveyAdminDataService;
        private readonly IEmailService _emailService;
        private readonly IDataCache _dataCache;
        private readonly IMapper _mapper;

        public MessageAdminController(IMessageAdminDataService messageAdminDataService, ISurveyAdminDataService surveyAdminDataService, IEmailService emailService, IDataCache dataCache, IMapper mapper)
        {
            _messageAdminDataService = messageAdminDataService;
            _surveyAdminDataService = surveyAdminDataService;
            _emailService = emailService;
            _dataCache = dataCache;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult RemoveSupportMessage(int messageId)
        {
            _messageAdminDataService.DeleteSupportMessage(messageId);
            return RedirectToAction("DevPage", "Home");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult ReadConversation(int messageId)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            Conversation cm = _messageAdminDataService.ReadConversation(messageId);
            var cvm = _mapper.Map<Conversation, ConversationViewModel>(cm);

            return View(cvm);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult SupportMessages(int surveyId, int? page)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            var smvms = GetSortedSupportMessages(surveyId);
            var pageNumber = page ?? 1;
            var onePageOfSupportMessages = smvms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfSupportMessages = onePageOfSupportMessages;

            return View(onePageOfSupportMessages);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult ReadSupportMessage(int messageId)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            SendMessage sm = _messageAdminDataService.ReadSupportMessage(messageId);
            var smvm = _mapper.Map<SendMessageViewModel>(sm);
            return View(smvm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult DeleteReplyMessage(SendMessageViewModel smvm, string action)
        {
            if (action.Equals(PageButtons.DeleteMessage))
            {
                int surveyId = _surveyAdminDataService.GetCurrentUserSurveyId();
                var sm = _mapper.Map<SendMessage>(smvm);
                if (sm.ToSurveyId == surveyId)
                {
                    _messageAdminDataService.DeleteMessage(sm.MessageId, surveyId);
                }
            }
            else if (action.Equals(PageButtons.ReplyToMessage))
            {
                int surveyId = _surveyAdminDataService.GetCurrentUserSurveyId();
                var sm = _mapper.Map<SendMessage>(smvm);
                if (sm.ToSurveyId == surveyId || (User.IsInRole(MemberRoles.Administrator) && (sm.ToSurveyId == _dataCache.SupportSurveyId || sm.ToSurveyId == _dataCache.SupportAnonSurveyId)))
                {
                    return RedirectToAction("ReplyToMessage", new { messageId = sm.MessageId });
                }
            }

            return RedirectToAction("DevPage", "Home");
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ReplyToMessage(int messageId)
        {
            var sm = _messageAdminDataService.ReadSupportMessage(messageId);
            var smvm = _mapper.Map<SendMessageViewModel>(sm);

            smvm.FromSurveyId = sm.ToSurveyId;
            smvm.FromName = sm.ToName;
            smvm.IsFromDisabled = sm.IsToDisabled;

            smvm.ToSurveyId = sm.FromSurveyId;
            smvm.ToName = sm.FromName;
            smvm.IsToDisabled = sm.IsFromDisabled;

            smvm.Body = _emailService.PrependBody(sm.Body);

            return View("BroadcastMessage", smvm);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ActionResult BroadcastMessage()
        {
            var smvm = new SendMessageViewModel();

            Survey fromSurvey = _surveyAdminDataService.GetSurvey(_dataCache.SupportSurveyId);
            smvm.FromSurveyId = fromSurvey.SurveyId;
            smvm.FromName = fromSurvey.Name;
            smvm.IsFromDisabled = fromSurvey.IsDisabled;

            Survey toSurvey = _surveyAdminDataService.GetSurvey(_dataCache.BroadcastSurveyId);
            smvm.ToSurveyId = toSurvey.SurveyId;
            smvm.ToName = toSurvey.Name;
            smvm.IsToDisabled = toSurvey.IsDisabled;

            return View(smvm);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        [HttpPost]
        public ActionResult BroadcastMessage(SendMessageViewModel mvm)
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            if (ModelState.IsValid)
            {
                var m = _mapper.Map<SendMessage>(mvm);

                if (m.ToSurveyId == _dataCache.BroadcastSurveyId)
                {
                    if (_messageAdminDataService.BroadcastMessage(m))
                    {
                        return RedirectToAction("DevPage", "Home");
                    }
                }
                else
                {
                    if (_messageAdminDataService.SendMessage(m))
                    {
                        return RedirectToAction("DevPage", "Home");
                    }
                }
            }

            return View();
        }

        private IEnumerable<SendMessageViewModel> GetSortedSupportMessages(int surveyId)
        {
            var rm = _messageAdminDataService.GetReceivedMessages(surveyId);
            var rmvm = _mapper.Map<IEnumerable<SendMessage>, IList<SendMessageViewModel>>(rm);

            IEnumerable<SendMessageViewModel> smvms = rmvm.OrderByDescending(x => x.SendDate);
            return smvms;
        }
    }
}

JAM-Brilliance/Controllers/PictureController.cs
using System.Collections.Generic;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;

using AutoMapper;

using JAM.Core.Interfaces;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class PictureController : Controller
    {
        private readonly IPictureDataService _pictureDataService;
        private readonly ISurveyDataService _surveyDataService;
        private readonly IDiagnosticsService _diagnosticsService;
        private readonly IMapper _mapper;

        public PictureController(ISurveyDataService surveyDataService, IPictureDataService pictureDataService, IDiagnosticsService diagnosticsService, IMapper mapper)
        {
            _pictureDataService = pictureDataService;
            _surveyDataService = surveyDataService;
            _diagnosticsService = diagnosticsService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ShowMainPicture(int surveyid)
        {
            var spvm = new ShowPictureViewModel();
            spvm.OwnerSurveyId = surveyid;
            spvm.PictureId = _pictureDataService.GetPictureId(surveyid, 0);

            return View(spvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        [OutputCache(VaryByParam = "surveyId", Duration = 30)]
        public FileResult MainPictureDataFor(int surveyId)
        {
            Picture picture = _pictureDataService.GetMainPictureFor(surveyId);

            return CheckPicture(picture);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ShowMyPicture(int pictureId)
        {
            var spvm = new ShowPictureViewModel();
            spvm.PictureId = pictureId;

            return View(spvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult ShowOtherPicture(int surveyId, int idx)
        {
            var pvm = new ShowPictureViewModel();
            pvm.OwnerSurveyId = surveyId;
            pvm.PictureId = _pictureDataService.GetPictureId(surveyId, idx);

            return View(pvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        [OutputCache(VaryByParam = "pictureId", Duration = 30)]
        public FileResult OtherPictureData(int pictureId, int ownerSurveyId)
        {
            Picture picture = _pictureDataService.GetPicture(ownerSurveyId, pictureId);

            return CheckPicture(picture);
        }

        [Authorize(Roles = MemberRoles.Member)]
        [OutputCache(VaryByParam = "surveyId,idx", Duration = 30)]
        public FileResult OtherPictureDataFor(int surveyId, int idx)
        {
            int pictureId = _pictureDataService.GetPictureId(surveyId, idx);
            Picture picture = _pictureDataService.GetPicture(surveyId, pictureId);

            return CheckPicture(picture);
        }

        [Authorize(Roles = MemberRoles.Member)]
        [OutputCache(VaryByParam = "pictureId", Duration = 30, NoStore = true)]
        public FileResult MyPictureData(int pictureId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();
            Picture picture = _pictureDataService.GetPicture(surveyId, pictureId);

            if (picture != null && picture.ThePicture != null)
            {
                var result = File(picture.ThePicture, picture.ContentType);

                return result;
            }
            else
            {
                var countryCode = Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;
                var path = string.Format("/Content/images/ja/missing_{0}.jpg", countryCode);

                if (System.IO.File.Exists(Server.MapPath(path)))
                {
                    return File(path, "image/jpeg");
                }

                path = "/Content/images/ja/missing_sv.jpg";
                return File(path, "image/jpeg");
            }
        }

        [Authorize(Roles = MemberRoles.Member)]
        public RedirectToRouteResult SetMainPicture(int pictureId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();
            _pictureDataService.SetMainPicture(surveyId, pictureId);

            return RedirectToAction("MyPictures");
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyPictures()
        {
            ViewBag.CurrentPageId = PageIds.MyPage;

            int surveyId = _surveyDataService.GetCurrentUserSurveyId();

            _diagnosticsService.ThrowUnlessSurveyComplete();

            var pms = _pictureDataService.GetPictures(surveyId);
            var pvms = _mapper.Map<IEnumerable<Picture>, IList<PictureViewModel>>(pms);

            var mpvm = new MyPicturesViewModel();
            mpvm.Pictures = pvms;

            return View(mpvm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Member)]
        public ViewResult MyPictures(MyPicturesViewModel myp)
        {
            HttpPostedFileBase pictureFile = Request.Files["pictureFile"];
            var pic = _pictureDataService.LoadBytesIntoPicture(pictureFile);

            int surveyId = _surveyDataService.GetCurrentUserSurveyId();
            
            if (pic != null)
            {
                pic.SurveyId = surveyId;
                int pictureId = _pictureDataService.SaveNewPicture(pic);

                if (pictureId == 0)
                {
                    var fel = "Du får ha max 5 bilder.";
                    ModelState.AddModelError("PictureDummyId", fel);
                }
            }
            else
            {
                var fel = "En bild får vara max 500kb stor och måste vara jpeg eller png.";
                ModelState.AddModelError("PictureDummyId", fel);
            }

            var pms = _pictureDataService.GetPictures(surveyId);
            var pvms = _mapper.Map<IEnumerable<Picture>, IList<PictureViewModel>>(pms);

            var mpvm = new MyPicturesViewModel();
            mpvm.Pictures = pvms;

            return View(mpvm);
        }

        [Authorize(Roles = MemberRoles.Member)]
        public ActionResult RemovePicture(int pictureId)
        {
            int surveyId = _surveyDataService.GetCurrentUserSurveyId();
            _pictureDataService.DeletePicture(surveyId, pictureId);

            return RedirectToAction("MyPictures");
        }

        private FileResult CheckPicture(Picture picture)
        {
            if (picture != null && !picture.IsApproved)
            {
                var countryCode = Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;
                var path = string.Format("/Content/images/ja/missing_{0}.jpg", countryCode);

                if (System.IO.File.Exists(Server.MapPath(path)))
                {
                    return File(path, "image/jpeg");
                }

                path = "/Content/images/ja/missing_sv.jpg";
                return File(path, "image/jpeg");
            }
            else if (picture != null && picture.ThePicture != null)
            {
                var result = File(picture.ThePicture, picture.ContentType);

                return result;
            }
            else
            {
                return File("/Content/images/ja/t.png", "image/png");
            }
        }
    }
}

JAM-Brilliance/Views/MessageAdmin/BroadcastMessage.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@model SendMessageViewModel

@section scripts{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

@{ Html.RenderAction("ToolbarAdmin", "Home"); }

<p>
    @using (Html.BeginForm("BroadcastMessage", "MessageAdmin"))
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>Skicka meddelande</legend>
            
            <img src="/Content/images/ja/logo.png" height="100" style="float: right;" />
            
            <div class="editor-label">
            </div>
            <div class="editor-field">
                @Html.HiddenFor(model => model.MessageId)
                @Html.HiddenFor(model => model.FromSurveyId)
                @Html.HiddenFor(model => model.ToSurveyId)
                @if (Model.IsFromDisabled)
                {
                    @Model.FromName.GetBeginning(StringLength.Short)
                }
                else
                {
                    @Html.ActionLink(Model.FromName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.FromSurveyId }, new { title = "Från" })
                }
                <span><i class="fa fa-long-arrow-right"></i></span>
                @if (Model.IsToDisabled)
                {
                    @Model.ToName.GetBeginning(StringLength.Short)
                }
                else
                {
                    @Html.ActionLink(Model.ToName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.ToSurveyId }, new { title = "Till" })
                }
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Body)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Body, new { rows = "8", cols = "50" })<br />
                @Html.ValidationMessageFor(model => model.Body)
            </div>

            <div>
                <br />
                <button type="submit">
                    Skicka <i class="fa fa-send"></i>
                </button>

            </div>
        </fieldset>
    }
</p>

JAM-Brilliance/Views/MessageAdmin/ReadConversation.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@model ConversationViewModel

@{ Html.RenderAction("ToolbarAdmin", "Home"); }

<p>
    <fieldset>
        <legend>
            En konversation mellan @Html.ActionLink(Model.OriginalMessage.FromName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.OriginalMessage.FromSurveyId }, null)
            <span><i class="fa fa-exchange"></i></span> @Html.ActionLink(Model.OriginalMessage.ToName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.OriginalMessage.ToSurveyId }, null)
        </legend>
        <br />
        @foreach (var m in Model.Messages.OrderBy(x => x.SendDate))
        {
            string styles;
            if (m.FromSurveyId == Model.OriginalMessage.FromSurveyId)
            {
                if (m.MessageId == Model.OriginalMessage.MessageId)
                {
                    styles = "width: 300px; border: 5px solid black;";
                }
                else
                {
                    styles = "width: 300px; border: 2px solid black;";
                }
            }
            else
            {
                if (m.MessageId == Model.OriginalMessage.MessageId)
                {
                    styles = "width: 300px; margin-left: 100px; border: 5px solid blue;";
                }
                else
                {
                    styles = "width: 300px; margin-left: 100px; border: 2px solid blue;";
                }
            }
           
            <table class="list-table" style="@styles">
                <tr><td style="background-color: lightgrey;">&nbsp;<i class="fa fa-envelope"></i> @m.FromName.GetBeginning(StringLength.Short)
                <span><i class="fa fa-long-arrow-right"></i></span> @m.ToName.GetBeginning(StringLength.Short)</td>
                </tr>
                <tr>
                    <td><textarea cols="35" rows="5" readonly="readonly">@m.Body</textarea></td>
                </tr>
            </table>
            <br/>
        }
    </fieldset>
</p>

JAM-Brilliance/Views/MessageAdmin/ReadSupportMessage.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@model SendMessageViewModel

@{ Html.RenderAction("ToolbarAdmin", "Home"); }

<div>
    @using (Html.BeginForm("DeleteReplyMessage", "MessageAdmin"))
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>Ett meddelande</legend>

            <div class="editor-label">
            </div>
            <div class="editor-field">
                @Html.HiddenFor(model => model.MessageId)
                @Html.HiddenFor(model => model.FromSurveyId)
                @Html.HiddenFor(model => model.ToSurveyId)
                @if (Model.IsFromDisabled)
                {
                    @Model.FromName.GetBeginning(StringLength.Short)
                }
                else
                {
                    @Html.ActionLink(Model.FromName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.FromSurveyId }, new { title = "Från" })
                }
                <span><i class="fa fa-long-arrow-right"></i></span>
                @if (Model.IsToDisabled)
                {
                    @Model.ToName.GetBeginning(StringLength.Short)
                }
                else
                {
                    @Html.ActionLink(Model.ToName.GetBeginning(StringLength.Short), "ShortDetails", "Survey", new { surveyId = Model.ToSurveyId }, new { title = "Till" })
                }
                <br />
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Body)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Body, new { rows = "8", cols = "50", @readonly = "readonly" })<br />
            </div>

            <div>
                <br />
                @if (Model.IsFromDisabled)
                {
                    <p><strong>Användaren är inte aktiv</strong></p>
                }

                @if (!Model.IsSentMessage)
                {
                    <button name="action" value="@PageButtons.ReplyToMessage" type="submit">
                        Svara <i class="fa fa-mail-reply"></i>
                    </button>
                    <button name="action" value="@PageButtons.DeleteMessage" type="submit">
                        Radera <i class="fa fa-trash"></i>
                    </button>
                    <button onclick="window.location.href = '@Url.Action("ReportMessage", "Abuse", new {messageId = Model.MessageId, fromSurveyId = Model.FromSurveyId})';" type="button">
                        Anmäl meddelande <i class="fa fa-bullhorn"></i>
                    </button>
                }
                else
                {
                    <p>Meddelandet går inte att svara på</p>
                }
            </div>
        </fieldset>
    }
</div>

JAM-Brilliance/Views/MessageAdmin/SupportMessages.cshtml
@using JAM.Core.Logic
@using JAM.Brilliance.Models.ViewModels
@using PagedList
@using PagedList.Mvc
@model IEnumerable<SendMessageViewModel>

@section scripts {
    <script type="text/javascript" src="@Url.Content("~/Scripts/ja/JamListTools.js")"></script>
}

@{ Html.RenderAction("ToolbarAdmin", "Home"); }

<p>
    <h4>Meddelande till support</h4>

    <table class="list-table">
        <tr>
            <th>Bild</th>
            <th>Till</th>
            <th>Från</th>
            <th>Meddelande</th>
            <th>Mottaget <i class="fa fa-chevron-down"></i></th>
            <th>Ta bort</th>
        </tr>
        @foreach (var smvm in Model)
        {
            <tr data-url="@Url.Action("ReadSupportMessage", new { messageId = smvm.MessageId })">
                <td data-action="highlightCell"><img class="list-picture" src="@Url.Action("MainPictureDataFor", "Picture", new { surveyId = smvm.FromSurveyId })" /></td>

                <td data-action="highlightCell" class="padded-table-cell@(smvm.IsUnread ? "-unread" : "")">@smvm.ToSurveyId</td>
                <td data-action="highlightCell" class="padded-table-cell@(smvm.IsUnread ? "-unread" : "")">@smvm.FromName.GetBeginning(StringLength.Short)</td>
                <td data-action="highlightCell" class="padded-table-cell@(smvm.IsUnread ? "-unread" : "")">@smvm.Body.GetBeginning(StringLength.Long)</td>
                <td data-action="highlightCell" class="padded-table-cell@(smvm.IsUnread ? "-unread" : "")">@smvm.SendDate</td>
                <td class="padded-table-cell-centered">
                    <a href="@Url.Action("RemoveSupportMessage", new { messageId = smvm.MessageId })" onclick="return confirm('Are you sure?');">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </table>
    @if (ViewBag.OnePageOfSupportMessages != null)
    {
        @Html.PagedListPager((IPagedList)ViewBag.OnePageOfSupportMessages, page => Url.Action("SupportMessages", new { surveyId = Model.First().ToSurveyId, page }))
        <br />
        <br />
        <br />
    }
</p>