JAM-Brilliance/Controllers/AccountAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.SessionState;

using AutoMapper;
using JAM.Core.Interfaces;
using JAM.Core.Interfaces.Admin;
using JAM.Core.Logic;
using JAM.Core.Models;
using JAM.Brilliance.Models.ViewModels;
using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.ReadOnly)]
    public class AccountAdminController : Controller
    {
        private readonly IAccountAdminService _accountAdminService;
        private readonly IEmailService _mailService;
        private readonly IEmailDataService _mailDataService;
        private readonly ILogDataService _logDataService;
        private readonly ISurveyAdminDataService _surveyAdminDataService;
        private readonly IMapper _mapper;

        public AccountAdminController(IAccountAdminService accountAdminService, IEmailService mailService, IEmailDataService mailDataService, ILogDataService logDataService, ISurveyAdminDataService surveyAdminDataService, IMapper mapper)
        {
            _accountAdminService = accountAdminService;
            _mailService = mailService;
            _mailDataService = mailDataService;
            _logDataService = logDataService;
            _surveyAdminDataService = surveyAdminDataService;
            _mapper = mapper;
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult AddRole(string userName, string roleName)
        {
            _accountAdminService.AddRoleToUser(userName, roleName);

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult Start(int? page)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            IList<RoleViewModel> rvms = new List<RoleViewModel>();
            string[] roles = Roles.GetAllRoles();
            foreach (var role in roles)
            {
                var rvm = new RoleViewModel();
                rvm.RoleName = role;
                rvm.Users = Roles.GetUsersInRole(role);
                rvms.Add(rvm);
            }

            MembershipUserCollection accounts = Membership.GetAllUsers();
            var ams = _mapper.Map<MembershipUserCollection, IList<Account>>(accounts);
            var avms = _mapper.Map<IList<Account>, IList<AccountViewModel>>(ams);
            var savms = avms.OrderBy(x => x.UserName);

            foreach (var avm in savms)
            {
                avm.Roles = Roles.GetRolesForUser(avm.UserName);
            }

            var pageNumber = page ?? 1;
            var onePageOfAccounts = savms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfAccounts = onePageOfAccounts;

            var arvm = new AccountsRolesViewModel();
            arvm.Accounts = onePageOfAccounts;
            arvm.Roles = rvms;

            return View(arvm);
        }

        //[Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult Setup()
        {
            _accountAdminService.CreateAllRoles();
            _accountAdminService.SetupSpecialUser();

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartOne(string emailfilter)
        {
            MembershipUserCollection accounts = Membership.FindUsersByEmail(emailfilter);
            var ams = _mapper.Map<MembershipUserCollection, IList<Account>>(accounts);
            var avms = _mapper.Map<IList<Account>, IList<AccountViewModel>>(ams);
            foreach (var avm in avms)
            {
                avm.Roles = Roles.GetRolesForUser(avm.UserName);
            }

            var onePageOfAccounts = avms.ToPagedList(1, Constants.PageSize);
            ViewBag.OnePageOfAccounts = onePageOfAccounts;

            var arvm = new AccountsRolesViewModel();
            arvm.Accounts = onePageOfAccounts;
            arvm.Roles = new List<RoleViewModel>();

            return View("Start", arvm);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult ActivateUser(string userName)
        {
            _accountAdminService.MakeUserMember(userName);

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult BlockUser(string email)
        {
            _accountAdminService.MakeUserBlocked(email);

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult ResetUserPassword(string userName)
        {
            var user = Membership.GetUser(userName);
            var password = user.ResetPassword();

            var cpm = new ChangePasswordViewModel();
            cpm.OldPassword = password;

            return View("NewPassword", cpm);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ActionResult ResendMail(string userName)
        {
            var user = Membership.GetUser(userName);
            if (user != null)
            {
                Guid guid = _mailDataService.GetVerificationGuid(user.Email);
                if (guid != Guid.Empty)
                {
                    string activationUrl = Url.Action("EmailVerification", "Account", new { uid = guid }, Request.Url.Scheme);

                    bool ok = _mailService.SendVerificationMail(user.UserName, user.Email, activationUrl);
                }
            }

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult DeleteFromAccount(string userName)
        {
            MembershipUser user = Membership.GetUser(userName);

            var surveyId = _surveyAdminDataService.GetSurveyId(user.Email);
            var survey = _surveyAdminDataService.GetSurvey(surveyId);
            if (survey == null) // will not be null since id will be 0 if fail
            {
                survey = new Survey();
                survey.Name = userName;
                survey.PostalCode = "Ingen profil";
                survey.City = "Ingen profil";
            }

            var ssvm = _mapper.Map<ShortSurveyViewModel>(survey);
            ssvm.Note1 = user.Email;

            return View("Delete", ssvm);
        }

        [HttpPost]
        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult Delete(ShortSurveyViewModel ssvm)
        {
            if (ssvm.SurveyId >= 10)
            {
                _surveyAdminDataService.DeleteSurvey(ssvm.SurveyId);
            }

            string email = ssvm.Note1;
            var userName = Membership.GetUserNameByEmail(email);
            Membership.DeleteUser(userName, true);

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult LogEntries(int? page)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            IEnumerable<LogEntry> lems = _logDataService.GetSortedLogEntries();
            var levms = _mapper.Map<IEnumerable<LogEntry>, IList<LogEntryViewModel>>(lems);

            var pageNumber = page ?? 1;
            var onePageOfLogEntries = levms.ToPagedList(pageNumber, Constants.PageSize);
            ViewBag.OnePageOfLogEntries = onePageOfLogEntries;

            return View(onePageOfLogEntries);
        }
    }
}

JAM-Brilliance/Controllers/SurveyAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;

using JAM.Core.Interfaces.Admin;
using JAM.Core.Logic;
using JAM.Core.Models;

using PagedList;

namespace JAM.Brilliance.Controllers
{
    [SessionState(SessionStateBehavior.ReadOnly)]
    [Authorize(Roles = MemberRoles.Administrator)]
    public class SurveyAdminController : Controller
    {
        private readonly ISurveyAdminDataService _surveyAdminDataService;

        public SurveyAdminController(ISurveyAdminDataService surveyAdminDataService)
        {
            _surveyAdminDataService = surveyAdminDataService;
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult Start(string sortOrder, string searchString, int? page)
        {
            IEnumerable<Survey> surveys = _surveyAdminDataService.GetSurveys().Where(s => !s.IsDisabled);

            return IndexFiltered(surveys, sortOrder, searchString, page);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartMen(string sortOrder, string searchString, int? page)
        {
            var surveys = _surveyAdminDataService.GetSurveys().Where(s => s.IsMale && !s.IsDisabled && !s.IsInterviewed);

            return IndexFiltered(surveys, sortOrder, searchString, page);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartWomen(string sortOrder, string searchString, int? page)
        {
            var surveys = _surveyAdminDataService.GetSurveys().Where(s => !s.IsMale && !s.IsDisabled && !s.IsInterviewed);

            return IndexFiltered(surveys, sortOrder, searchString, page);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartAll(string sortOrder, string searchString, int? page)
        {
            var surveys = _surveyAdminDataService.GetSurveys().Select(s => s);

            return IndexFiltered(surveys, sortOrder, searchString, page);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartProspects(string sortOrder, string searchString, int? page)
        {
            var surveys = _surveyAdminDataService.GetSurveys().Where(s => s.IsInterviewed && !s.IsDisabled);

            return IndexFiltered(surveys, sortOrder, searchString, page);
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult Hide(int surveyId)
        {
            _surveyAdminDataService.HideSurvey(surveyId);

            return RedirectToAction("Start");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public RedirectToRouteResult UnHide(int surveyId)
        {
            _surveyAdminDataService.UnhideSurvey(surveyId);

            return RedirectToAction("StartAll");
        }

        [Authorize(Roles = MemberRoles.Administrator)]
        public ViewResult StartOne(string emailFilter)
        {
            var surveys = _surveyAdminDataService.GetSurveys().Where(s => s.Email == emailFilter);

            var onePageOfSurveys = surveys.ToPagedList(1, Constants.PageSize);

            ViewBag.OnePageOfSurveys = onePageOfSurveys;

            return View("Start", onePageOfSurveys);
        }

        private ViewResult IndexFiltered(IEnumerable<Survey> surveys, string sortOrder, string searchString, int? page)
        {
            ViewBag.CurrentPageId = PageIds.DevPage;

            ViewBag.IdSortParm = string.IsNullOrEmpty(sortOrder) ? "IdDesc" : "Id";
            ViewBag.NameSortParm = sortOrder == "Name" ? "NameDesc" : "Name";
            ViewBag.CitySortParm = sortOrder == "City" ? "CityDesc" : "City";
            ViewBag.SearchString = searchString;

            var filteredSurveys = surveys;
            if (!string.IsNullOrEmpty(searchString))
            {
                filteredSurveys = filteredSurveys.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper())
                                        || s.City.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Name":
                    filteredSurveys = filteredSurveys.OrderBy(s => s.Name);
                    break;

                case "NameDesc":
                    filteredSurveys = filteredSurveys.OrderByDescending(s => s.Name);
                    break;

                case "City":
                    filteredSurveys = filteredSurveys.OrderBy(s => s.City);
                    break;

                case "CityDesc":
                    filteredSurveys = filteredSurveys.OrderByDescending(s => s.City);
                    break;

                case "Id":
                    filteredSurveys = filteredSurveys.OrderBy(s => s.SurveyId);
                    break;

                case "IdDesc":
                    filteredSurveys = filteredSurveys.OrderByDescending(s => s.SurveyId);
                    break;

                default:
                    filteredSurveys = filteredSurveys.OrderByDescending(s => s.SurveyId);
                    break;
            }

            var pageNumber = page ?? 1;
            IPagedList<Survey> onePageOfSurveys = filteredSurveys.ToPagedList(pageNumber, Constants.PageSize);

            ViewBag.OnePageOfSurveys = onePageOfSurveys;

            return View("Start", onePageOfSurveys);
        }
    }
}

JAM-Brilliance/Views/AccountAdmin/Delete.cshtml
@using JAM.Brilliance.Models.ViewModels;
@model ShortSurveyViewModel

<div>
    <h2>
        Vill du verkligen ta bort den här profilen?<br/>
        Inklusive login, bilder, meddelande, favoriter, historik
    </h2>
    <br />
    @using (Html.BeginForm("Delete", "AccountAdmin"))
    {    <fieldset>
        <legend>Radera den här profilen, inklusive login, bilder, meddelande, favoriter, historik</legend>
        <div class="editor-label">
            <b>Namn</b>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Name)
        </div>
        <div class="editor-label">
            <b>Postnummer</b>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.PostalCode)
        </div>
        <div class="editor-label">
            <b>Stad</b>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.City)
        </div>
        <div class="editor-label">
            <b>Email</b>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Note1)
            @Html.HiddenFor(model => model.Note1)
        </div>
    </fieldset>

        <p>

            <div class="editor-field">
                @Html.HiddenFor(model => model.SurveyId)
            </div>
            <button type="submit">
                Ta bort <i class="fa fa-trash-o"></i>
            </button>
            |
            @Html.ActionLink("Tillbaka till listan", "Start")
        </p>
    }
</div>

JAM-Brilliance/Views/AccountAdmin/LogEntries.cshtml
@using JAM.Brilliance.Models.ViewModels
@using PagedList
@using PagedList.Mvc
@model IEnumerable<LogEntryViewModel>

<div>
    @{ Html.RenderAction("ToolbarAdmin", "Home"); }
    <p>
        <table class="list-table">
            <tr>
                <th>ID</th>
                <th>Användarnamn</th>
                <th>IP Nummer</th>
                <th>Host</th>
                <th>Machine</th>
                <th>Level</th>
                <th>Meddelande</th>
                <th>Datum <i class="fa fa-chevron-down"></i></th>
            </tr>
            @foreach (LogEntryViewModel logEntry in Model)
            {
                <tr>
                    <td>@logEntry.Id</td>
                    <td>@logEntry.UserName</td>
                    <td>@logEntry.Ip</td>
                    <td>@logEntry.HostName</td>
                    <td>@logEntry.MachineName</td>
                    <td>@logEntry.EventLevel</td>
                    <td>@logEntry.EventMessage</td>
                    <td>@logEntry.EventDateTime</td>
                </tr>
            }
        </table>
        @Html.PagedListPager((IPagedList)ViewBag.OnePageOfLogEntries, page => Url.Action("LogEntries", new { page }))
    </p>
    @Html.ActionLink("ELMAH", "GotoElmah", "Home")
</div>

JAM-Brilliance/Views/AccountAdmin/NewPassword.cshtml
@using JAM.Brilliance.Models.ViewModels;
@model ChangePasswordViewModel

<div>
    <h2>
        New password
    </h2>
    <p>
        @Model.OldPassword
    </p>
</div>

JAM-Brilliance/Views/AccountAdmin/Start.cshtml
@using JAM.Brilliance.Models.ViewModels
@using JAM.Core.Logic
@using PagedList
@using PagedList.Mvc
@model AccountsRolesViewModel

<div>
    @{ Html.RenderAction("ToolbarAdmin", "Home"); }
    <p>
        <table class="list-table">
            <tr>
                <th>Namn <i class="fa fa-chevron-up"></i></th>
                <th>E-Post</th>
                <th>Roller</th>
                <th>Senaste aktivitet</th>
                <th title="Approved/LockedOut/Online">A/L/O</th>
                <th colspan="4">Åtgärder</th>
                <th>X</th>
            </tr>
            @foreach (AccountViewModel user in Model.Accounts)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>@Html.ActionLink(user.Email, "StartOne", "SurveyAdmin", new { emailFilter = user.Email }, null)</td>
                    <td>@string.Join(", ", user.Roles)
                        <a href="@Url.Action("AddRole", new { userName = user.UserName, roleName = MemberRoles.MobileApp })" title="Lägg till MobileApp roll"><i class="fa fa-plus-square-o"></i></a>
                        <a href="@Url.Action("AddRole", new { userName = user.UserName, roleName = MemberRoles.Administrator})" title="Lägg till Administrator roll"><i class="fa fa-plus-circle"></i></a>
                        <a href="@Url.Action("AddRole", new { userName = user.UserName, roleName = MemberRoles.Member})" title="Lägg till Member roll"><i class="fa fa-plus-square"></i></a>
                    </td>
                    <td>@user.LastActivityDate</td>
                    <td>@(user.IsApproved ? "A" : "") @(user.IsLockedOut ? "L" : "") @(user.IsOnline ? "O" : "")</td>
                    <td>@Html.ActionLink("Aktivera", "ActivateUser", new { userName = user.UserName })</td>
                    <td>@Html.ActionLink("Spärra", "BlockUser", new { email = user.Email })&nbsp;</td>
                    <td>@Html.ActionLink("Återställ", "ResetUserPassword", new { userName = user.UserName })</td>
                    <td>@Html.ActionLink("Skicka Igen", "ResendMail", new { userName = user.UserName })</td>
                    <td class="padded-table-cell-centered"><a href="@Url.Action("DeleteFromAccount", new { userName = user.UserName })" title="Ta bort"><i class="fa fa-trash"></i></a></td>
                </tr>
            }
        </table>
        @Html.PagedListPager((IPagedList)ViewBag.OnePageOfAccounts, page => Url.Action("Start", new { page }))
    </p>
    
    @if (Model.Roles.Any())
    {
        <h2>
            Roller
        </h2>
        <p>
            <ul>
                @foreach (var role in Model.Roles)
                {
                    <li>@role.RoleName (@string.Join(", ", role.Users))</li>
                }
            </ul>
        </p>
    }
</div>